import { Project } from "../features/projects/models/project.model";

export const PROJECTS_MOCK_DATA: Project[] = [
  {
    id: 1,
    name: 'Website Redesign',
    createdDate: '2024-11-01',
    createdBy: 'John Doe',
    included: true,
    integration: 'Jira',
    description: 'Redesign the company website for better UX.',
    hours: 120,
    timeRecords: 50,
  },
  {
    id: 2,
    name: 'Marketing Campaign',
    createdDate: '2024-10-15',
    createdBy: 'Jane Smith',
    included: false,
    integration: 'Asana',
    description: 'Plan and execute the holiday marketing campaign.',
    hours: 80,
    timeRecords: 30,
  },
  {
    id: 3,
    name: 'Mobile App Development',
    createdDate: '2024-09-20',
    createdBy: 'Sarah Lee',
    included: true,
    integration: 'Trello',
    description: 'Develop a mobile app for customer engagement.',
    hours: 200,
    timeRecords: 100,
  },
  {
    id: 4,
    name: 'Data Migration',
    createdDate: '2024-08-05',
    createdBy: 'Mark Johnson',
    included: true,
    integration: 'Monday.com',
    description: 'Migrate all legacy data to the new system.',
    hours: 150,
    timeRecords: 75,
  },
  {
    id: 5,
    name: 'Product Launch Event',
    createdDate: '2024-07-12',
    createdBy: 'Emily Carter',
    included: false,
    integration: 'ClickUp',
    description: 'Organize and execute the launch event for the new product.',
    hours: 90,
    timeRecords: 40,
  },
];
